// Code generated by a2uigen; DO NOT EDIT.

package a2ui

import "github.com/a2ui-project/a2ui/go/a2ui/v09"

// Version re-exports the protocol version from the active implementation.
const Version = v09.Version

// Hand-written message types.
type (
	ServerMessage = v09.ServerMessage
	ClientMessage = v09.ClientMessage
)

// Hand-written server-to-client message types.
type (
	CreateSurface    = v09.CreateSurface
	UpdateComponents = v09.UpdateComponents
	UpdateDataModel  = v09.UpdateDataModel
	DeleteSurface    = v09.DeleteSurface
)

// Hand-written client-to-server message types.
type (
	ActionEvent = v09.ActionEvent
	ClientError = v09.ClientError
)

// Hand-written common types.
type (
	Component               = v09.Component
	DynamicString           = v09.DynamicString
	DynamicNumber           = v09.DynamicNumber
	DynamicBoolean          = v09.DynamicBoolean
	DynamicStringList       = v09.DynamicStringList
	DynamicValue            = v09.DynamicValue
	DataBinding             = v09.DataBinding
	FunctionCall            = v09.FunctionCall
	ChildList               = v09.ChildList
	ChildTemplate           = v09.ChildTemplate
	CheckRule               = v09.CheckRule
	AccessibilityAttributes = v09.AccessibilityAttributes
	Theme                   = v09.Theme
	Action                  = v09.Action
	EventAction             = v09.EventAction
	IconNameOrPath          = v09.IconNameOrPath
)

// Capability types.
type (
	ClientCapabilities    = v09.ClientCapabilities
	ClientCapabilitiesV09 = v09.ClientCapabilitiesV09
	ServerCapabilities    = v09.ServerCapabilities
	ServerCapabilitiesV09 = v09.ServerCapabilitiesV09
	CatalogDef            = v09.CatalogDef
	FunctionDefinition    = v09.FunctionDefinition
	ClientDataModel       = v09.ClientDataModel
)

// Generated component types.
type (
	AudioPlayerComponent   = v09.AudioPlayerComponent
	ButtonComponent        = v09.ButtonComponent
	CardComponent          = v09.CardComponent
	CheckBoxComponent      = v09.CheckBoxComponent
	ChoicePickerComponent  = v09.ChoicePickerComponent
	ColumnComponent        = v09.ColumnComponent
	DateTimeInputComponent = v09.DateTimeInputComponent
	DividerComponent       = v09.DividerComponent
	IconComponent          = v09.IconComponent
	ImageComponent         = v09.ImageComponent
	ListComponent          = v09.ListComponent
	ModalComponent         = v09.ModalComponent
	RowComponent           = v09.RowComponent
	SliderComponent        = v09.SliderComponent
	TabsComponent          = v09.TabsComponent
	TextComponent          = v09.TextComponent
	TextFieldComponent     = v09.TextFieldComponent
	VideoComponent         = v09.VideoComponent
)

// Generated inline struct types.
type (
	TabDef       = v09.TabDef
	ChoiceOption = v09.ChoiceOption
)

// Generated message list-wrapper types.
type (
	ClientMessageListWrapper = v09.ClientMessageListWrapper
	ServerMessageListWrapper = v09.ServerMessageListWrapper
)

// Generated enum types.
type (
	ReturnType               = v09.ReturnType
	IconName                 = v09.IconName
	ButtonVariant            = v09.ButtonVariant
	ChoicePickerDisplayStyle = v09.ChoicePickerDisplayStyle
	ChoicePickerVariant      = v09.ChoicePickerVariant
	DividerAxis              = v09.DividerAxis
	ImageFit                 = v09.ImageFit
	ImageVariant             = v09.ImageVariant
	LayoutAlign              = v09.LayoutAlign
	LayoutJustify            = v09.LayoutJustify
	ListDirection            = v09.ListDirection
	TextFieldVariant         = v09.TextFieldVariant
	TextVariant              = v09.TextVariant
)

// ReturnType constants.
const (
	ReturnTypeString  = v09.ReturnTypeString
	ReturnTypeNumber  = v09.ReturnTypeNumber
	ReturnTypeBoolean = v09.ReturnTypeBoolean
	ReturnTypeArray   = v09.ReturnTypeArray
	ReturnTypeObject  = v09.ReturnTypeObject
	ReturnTypeAny     = v09.ReturnTypeAny
	ReturnTypeVoid    = v09.ReturnTypeVoid
)

// Icon constants.
const (
	IconAccountCircle    = v09.IconAccountCircle
	IconAdd              = v09.IconAdd
	IconArrowBack        = v09.IconArrowBack
	IconArrowForward     = v09.IconArrowForward
	IconAttachFile       = v09.IconAttachFile
	IconCalendarToday    = v09.IconCalendarToday
	IconCall             = v09.IconCall
	IconCamera           = v09.IconCamera
	IconCheck            = v09.IconCheck
	IconClose            = v09.IconClose
	IconDelete           = v09.IconDelete
	IconDownload         = v09.IconDownload
	IconEdit             = v09.IconEdit
	IconEvent            = v09.IconEvent
	IconError            = v09.IconError
	IconFastForward      = v09.IconFastForward
	IconFavorite         = v09.IconFavorite
	IconFavoriteOff      = v09.IconFavoriteOff
	IconFolder           = v09.IconFolder
	IconHelp             = v09.IconHelp
	IconHome             = v09.IconHome
	IconInfo             = v09.IconInfo
	IconLocationOn       = v09.IconLocationOn
	IconLock             = v09.IconLock
	IconLockOpen         = v09.IconLockOpen
	IconMail             = v09.IconMail
	IconMenu             = v09.IconMenu
	IconMoreVert         = v09.IconMoreVert
	IconMoreHoriz        = v09.IconMoreHoriz
	IconNotificationsOff = v09.IconNotificationsOff
	IconNotifications    = v09.IconNotifications
	IconPause            = v09.IconPause
	IconPayment          = v09.IconPayment
	IconPerson           = v09.IconPerson
	IconPhone            = v09.IconPhone
	IconPhoto            = v09.IconPhoto
	IconPlay             = v09.IconPlay
	IconPrint            = v09.IconPrint
	IconRefresh          = v09.IconRefresh
	IconRewind           = v09.IconRewind
	IconSearch           = v09.IconSearch
	IconSend             = v09.IconSend
	IconSettings         = v09.IconSettings
	IconShare            = v09.IconShare
	IconShoppingCart     = v09.IconShoppingCart
	IconSkipNext         = v09.IconSkipNext
	IconSkipPrevious     = v09.IconSkipPrevious
	IconStar             = v09.IconStar
	IconStarHalf         = v09.IconStarHalf
	IconStarOff          = v09.IconStarOff
	IconStop             = v09.IconStop
	IconUpload           = v09.IconUpload
	IconVisibility       = v09.IconVisibility
	IconVisibilityOff    = v09.IconVisibilityOff
	IconVolumeDown       = v09.IconVolumeDown
	IconVolumeMute       = v09.IconVolumeMute
	IconVolumeOff        = v09.IconVolumeOff
	IconVolumeUp         = v09.IconVolumeUp
	IconWarning          = v09.IconWarning
)

// Enum constants.
const (
	ButtonVariantDefault                 = v09.ButtonVariantDefault
	ButtonVariantPrimary                 = v09.ButtonVariantPrimary
	ButtonVariantBorderless              = v09.ButtonVariantBorderless
	ChoicePickerDisplayStyleCheckbox     = v09.ChoicePickerDisplayStyleCheckbox
	ChoicePickerDisplayStyleChips        = v09.ChoicePickerDisplayStyleChips
	ChoicePickerVariantMultipleSelection = v09.ChoicePickerVariantMultipleSelection
	ChoicePickerVariantMutuallyExclusive = v09.ChoicePickerVariantMutuallyExclusive
	DividerAxisHorizontal                = v09.DividerAxisHorizontal
	DividerAxisVertical                  = v09.DividerAxisVertical
	ImageFitContain                      = v09.ImageFitContain
	ImageFitCover                        = v09.ImageFitCover
	ImageFitFill                         = v09.ImageFitFill
	ImageFitNone                         = v09.ImageFitNone
	ImageFitScaleDown                    = v09.ImageFitScaleDown
	ImageVariantIcon                     = v09.ImageVariantIcon
	ImageVariantAvatar                   = v09.ImageVariantAvatar
	ImageVariantSmallFeature             = v09.ImageVariantSmallFeature
	ImageVariantMediumFeature            = v09.ImageVariantMediumFeature
	ImageVariantLargeFeature             = v09.ImageVariantLargeFeature
	ImageVariantHeader                   = v09.ImageVariantHeader
	LayoutAlignCenter                    = v09.LayoutAlignCenter
	LayoutAlignEnd                       = v09.LayoutAlignEnd
	LayoutAlignStart                     = v09.LayoutAlignStart
	LayoutAlignStretch                   = v09.LayoutAlignStretch
	LayoutJustifyStart                   = v09.LayoutJustifyStart
	LayoutJustifyCenter                  = v09.LayoutJustifyCenter
	LayoutJustifyEnd                     = v09.LayoutJustifyEnd
	LayoutJustifySpaceBetween            = v09.LayoutJustifySpaceBetween
	LayoutJustifySpaceAround             = v09.LayoutJustifySpaceAround
	LayoutJustifySpaceEvenly             = v09.LayoutJustifySpaceEvenly
	LayoutJustifyStretch                 = v09.LayoutJustifyStretch
	ListDirectionVertical                = v09.ListDirectionVertical
	ListDirectionHorizontal              = v09.ListDirectionHorizontal
	TextFieldVariantLongText             = v09.TextFieldVariantLongText
	TextFieldVariantNumber               = v09.TextFieldVariantNumber
	TextFieldVariantShortText            = v09.TextFieldVariantShortText
	TextFieldVariantObscured             = v09.TextFieldVariantObscured
	TextVariantH1                        = v09.TextVariantH1
	TextVariantH2                        = v09.TextVariantH2
	TextVariantH3                        = v09.TextVariantH3
	TextVariantH4                        = v09.TextVariantH4
	TextVariantH5                        = v09.TextVariantH5
	TextVariantCaption                   = v09.TextVariantCaption
	TextVariantBody                      = v09.TextVariantBody
)

// Hand-written Dynamic* constructors.
var (
	StringLiteral     = v09.StringLiteral
	StringBinding     = v09.StringBinding
	StringFunc        = v09.StringFunc
	NumberLiteral     = v09.NumberLiteral
	NumberBinding     = v09.NumberBinding
	NumberFunc        = v09.NumberFunc
	BoolLiteral       = v09.BoolLiteral
	BoolBinding       = v09.BoolBinding
	BoolFunc          = v09.BoolFunc
	StringListLiteral = v09.StringListLiteral
	StringListBinding = v09.StringListBinding
	StringListFunc    = v09.StringListFunc
	ValueString       = v09.ValueString
	ValueNumber       = v09.ValueNumber
	ValueBool         = v09.ValueBool
	ValueArray        = v09.ValueArray
	ValueBinding      = v09.ValueBinding
	ValueFunc         = v09.ValueFunc
)

// Generated function constructors.
var (
	And            = v09.And
	Email          = v09.Email
	FormatCurrency = v09.FormatCurrency
	FormatDate     = v09.FormatDate
	FormatNumber   = v09.FormatNumber
	FormatString   = v09.FormatString
	Length         = v09.Length
	Not            = v09.Not
	Numeric        = v09.Numeric
	OpenURL        = v09.OpenURL
	Or             = v09.Or
	Pluralize      = v09.Pluralize
	Regex          = v09.Regex
	Required       = v09.Required
)
