// Code generated by a2uigen; DO NOT EDIT.

package a2ui

import (
	"encoding/json"
	"fmt"
)

// MarshalJSON encodes a [Component] as a flat JSON object with the "component"
// discriminator, common fields, and component-specific fields merged together.
func (c Component) MarshalJSON() ([]byte, error) {
	componentType, specific, count := c.componentData()
	switch count {
	case 0:
		return nil, fmt.Errorf("a2ui: component has no concrete type set")
	case 1:
	default:
		return nil, fmt.Errorf("a2ui: component has multiple concrete types set")
	}
	cm := struct {
		ComponentType string `json:"component"`
		componentCommon
	}{componentType, c.common()}

	commonBytes, err := json.Marshal(cm)
	if err != nil {
		return nil, err
	}

	specificBytes, err := json.Marshal(specific)
	if err != nil {
		return nil, err
	}

	// Merge: overwrite common with specific fields.
	if len(specificBytes) <= 2 { // "{}" or empty
		return commonBytes, nil
	}
	// Remove leading '{' from specific, append to common.
	merged := make([]byte, 0, len(commonBytes)+len(specificBytes))
	merged = append(merged, commonBytes[:len(commonBytes)-1]...) // drop trailing '}'
	merged = append(merged, ',')
	merged = append(merged, specificBytes[1:]...) // drop leading '{'
	return merged, nil
}

// UnmarshalJSON decodes a flat JSON object into a [Component], using the
// "component" field as the discriminator.
func (c *Component) UnmarshalJSON(data []byte) error {
	// Read the discriminator.
	var disc struct {
		ComponentType string `json:"component"`
	}
	if err := json.Unmarshal(data, &disc); err != nil {
		return err
	}

	// Unmarshal common fields.
	var cm componentCommon
	if err := json.Unmarshal(data, &cm); err != nil {
		return err
	}
	*c = Component{}
	c.setCommon(cm)

	// Unmarshal component-specific fields.
	switch disc.ComponentType {
	case "AudioPlayer":
		var v AudioPlayerComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.AudioPlayer = &v
	case "Button":
		var v ButtonComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Button = &v
	case "Card":
		var v CardComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Card = &v
	case "CheckBox":
		var v CheckBoxComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.CheckBox = &v
	case "ChoicePicker":
		var v ChoicePickerComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.ChoicePicker = &v
	case "Column":
		var v ColumnComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Column = &v
	case "DateTimeInput":
		var v DateTimeInputComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.DateTimeInput = &v
	case "Divider":
		var v DividerComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Divider = &v
	case "Icon":
		var v IconComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Icon = &v
	case "Image":
		var v ImageComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Image = &v
	case "List":
		var v ListComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.List = &v
	case "Modal":
		var v ModalComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Modal = &v
	case "Row":
		var v RowComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Row = &v
	case "Slider":
		var v SliderComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Slider = &v
	case "Tabs":
		var v TabsComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Tabs = &v
	case "Text":
		var v TextComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Text = &v
	case "TextField":
		var v TextFieldComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.TextField = &v
	case "Video":
		var v VideoComponent
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		c.Video = &v
	default:
		return fmt.Errorf("unknown component type: %s", disc.ComponentType)
	}
	return nil
}
