// Code generated by a2uigen; DO NOT EDIT.

package a2ui

// And creates a function call for "and".
// Performs a logical AND operation on a list of boolean values.
func And(values []DynamicBoolean) DynamicBoolean {
	args := map[string]any{
		"values": values,
	}
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "and",
		Args: args,
	}}
}

// Email creates a function call for "email".
// Checks that the value is a valid email address.
func Email(value DynamicString) DynamicValidationResult {
	args := map[string]any{
		"value": value,
	}
	return DynamicValidationResult{FunctionCall: &FunctionCall{
		Call: "email",
		Args: args,
	}}
}

// FormatCurrency creates a function call for "formatCurrency".
// Formats a number as a currency string.
// Optional arguments that are nil or zero are left out of the call.
func FormatCurrency(value DynamicNumber, currency DynamicString, decimals DynamicNumber, grouping DynamicBoolean) DynamicString {
	args := map[string]any{
		"value":    value,
		"currency": currency,
	}
	if decimals != (DynamicNumber{}) {
		args["decimals"] = decimals
	}
	if grouping != (DynamicBoolean{}) {
		args["grouping"] = grouping
	}
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatCurrency",
		Args: args,
	}}
}

// FormatDate creates a function call for "formatDate".
// Formats a timestamp into a string using a pattern.
func FormatDate(value DynamicValue, format DynamicString) DynamicString {
	args := map[string]any{
		"value":  value,
		"format": format,
	}
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatDate",
		Args: args,
	}}
}

// FormatNumber creates a function call for "formatNumber".
// Formats a number with the specified grouping and decimal precision.
// Optional arguments that are nil or zero are left out of the call.
func FormatNumber(value DynamicNumber, decimals DynamicNumber, grouping DynamicBoolean) DynamicString {
	args := map[string]any{
		"value": value,
	}
	if decimals != (DynamicNumber{}) {
		args["decimals"] = decimals
	}
	if grouping != (DynamicBoolean{}) {
		args["grouping"] = grouping
	}
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatNumber",
		Args: args,
	}}
}

// FormatString creates a function call for "formatString".
// Performs string interpolation of data model values and other functions in the catalog functions list and returns the resulting string. The value string can contain interpolated expressions in the `${expression}` format. Supported expression types include: JSON Pointer paths to the data model (e.g., `${/absolute/path}` or `${relative/path}`), and renderer-side function calls (e.g., `${now()}`). Function arguments must be named (e.g., `${formatDate(value:${/currentDate}, format:'MM-dd')}`). To include a literal `${` sequence, escape it as `\${`.
func FormatString(value DynamicString) DynamicString {
	args := map[string]any{
		"value": value,
	}
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatString",
		Args: args,
	}}
}

// Length creates a function call for "length".
// Checks string length constraints.
// Optional arguments that are nil or zero are left out of the call.
func Length(value DynamicString, min *int, max *int) DynamicValidationResult {
	args := map[string]any{
		"value": value,
	}
	if min != nil {
		args["min"] = *min
	}
	if max != nil {
		args["max"] = *max
	}
	return DynamicValidationResult{FunctionCall: &FunctionCall{
		Call: "length",
		Args: args,
	}}
}

// Not creates a function call for "not".
// Performs a logical NOT operation on a boolean value.
func Not(value DynamicBoolean) DynamicBoolean {
	args := map[string]any{
		"value": value,
	}
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "not",
		Args: args,
	}}
}

// Numeric creates a function call for "numeric".
// Checks numeric range constraints.
// Optional arguments that are nil or zero are left out of the call.
func Numeric(value DynamicNumber, min *float64, max *float64) DynamicValidationResult {
	args := map[string]any{
		"value": value,
	}
	if min != nil {
		args["min"] = *min
	}
	if max != nil {
		args["max"] = *max
	}
	return DynamicValidationResult{FunctionCall: &FunctionCall{
		Call: "numeric",
		Args: args,
	}}
}

// OpenURL creates a function call for "openUrl".
// Opens the specified URL in a browser or handler (requires user activation). This function has no return value.
func OpenURL(url DynamicString) Action {
	args := map[string]any{
		"url": url,
	}
	return Action{FunctionCall: &FunctionCall{
		Call: "openUrl",
		Args: args,
	}}
}

// Or creates a function call for "or".
// Performs a logical OR operation on a list of boolean values.
func Or(values []DynamicBoolean) DynamicBoolean {
	args := map[string]any{
		"values": values,
	}
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "or",
		Args: args,
	}}
}

// Pluralize creates a function call for "pluralize".
// Returns a localized string based on the Common Locale Data Repository (CLDR) plural category of the count (zero, one, two, few, many, other). Requires an 'other' fallback. For English, just use 'one' and 'other'.
// Optional arguments that are nil or zero are left out of the call.
func Pluralize(value DynamicNumber, other DynamicString, zero DynamicString, one DynamicString, two DynamicString, few DynamicString, many DynamicString) DynamicString {
	args := map[string]any{
		"value": value,
		"other": other,
	}
	if zero != (DynamicString{}) {
		args["zero"] = zero
	}
	if one != (DynamicString{}) {
		args["one"] = one
	}
	if two != (DynamicString{}) {
		args["two"] = two
	}
	if few != (DynamicString{}) {
		args["few"] = few
	}
	if many != (DynamicString{}) {
		args["many"] = many
	}
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "pluralize",
		Args: args,
	}}
}

// Regex creates a function call for "regex".
// Checks that the value matches a regular expression string.
func Regex(value DynamicString, pattern string) DynamicValidationResult {
	args := map[string]any{
		"value":   value,
		"pattern": pattern,
	}
	return DynamicValidationResult{FunctionCall: &FunctionCall{
		Call: "regex",
		Args: args,
	}}
}

// Required creates a function call for "required".
// Checks that the value is not null, undefined, or empty.
func Required(value DynamicValue) DynamicValidationResult {
	args := map[string]any{
		"value": value,
	}
	return DynamicValidationResult{FunctionCall: &FunctionCall{
		Call: "required",
		Args: args,
	}}
}
