// Code generated by a2uigen; DO NOT EDIT.

package v10

// AgentMessageListWrapper wraps a list of [AgentMessage] in a {"messages": [...]}
// envelope for transports that require a top-level JSON object.
type AgentMessageListWrapper struct {
	Messages []AgentMessage `json:"messages"`
}

// RendererMessageListWrapper wraps a list of [RendererMessage] in a {"messages": [...]}
// envelope for transports that require a top-level JSON object.
type RendererMessageListWrapper struct {
	Messages []RendererMessage `json:"messages"`
}
