// Code generated by a2uigen; DO NOT EDIT.

package v09

// ClientMessageListWrapper wraps a list of [ClientMessage] in a {"messages": [...]}
// envelope for transports that require a top-level JSON object.
type ClientMessageListWrapper struct {
	Messages []ClientMessage `json:"messages"`
}

// ServerMessageListWrapper wraps a list of [ServerMessage] in a {"messages": [...]}
// envelope for transports that require a top-level JSON object.
type ServerMessageListWrapper struct {
	Messages []ServerMessage `json:"messages"`
}
