// Code generated by a2uigen; DO NOT EDIT.

package v091

// TabDef defines a tab within a [Tabs] component.
type TabDef struct {
	Title DynamicString `json:"title"`
	Child string        `json:"child"`
}

// ChoiceOption defines a selectable option within a [ChoicePicker] component.
type ChoiceOption struct {
	Label DynamicString `json:"label"`
	Value string        `json:"value"`
}

// AudioPlayerComponent holds the component-specific fields for a AudioPlayer.
type AudioPlayerComponent struct {
	Description *DynamicString `json:"description,omitempty"`
	URL         DynamicString  `json:"url"`
}

// ButtonComponent holds the component-specific fields for a Button.
type ButtonComponent struct {
	Action  Action        `json:"action"`
	Child   string        `json:"child"`
	Variant ButtonVariant `json:"variant,omitempty"`
}

// CardComponent holds the component-specific fields for a Card.
type CardComponent struct {
	Child string `json:"child"`
}

// CheckBoxComponent holds the component-specific fields for a CheckBox.
type CheckBoxComponent struct {
	Label DynamicString  `json:"label"`
	Value DynamicBoolean `json:"value"`
}

// ChoicePickerComponent holds the component-specific fields for a ChoicePicker.
type ChoicePickerComponent struct {
	DisplayStyle ChoicePickerDisplayStyle `json:"displayStyle,omitempty"`
	Filterable   *bool                    `json:"filterable,omitempty"`
	Label        *DynamicString           `json:"label,omitempty"`
	Options      []ChoiceOption           `json:"options"`
	Value        DynamicStringList        `json:"value"`
	Variant      ChoicePickerVariant      `json:"variant,omitempty"`
}

// ColumnComponent holds the component-specific fields for a Column.
type ColumnComponent struct {
	Align    LayoutAlign   `json:"align,omitempty"`
	Children ChildList     `json:"children"`
	Justify  LayoutJustify `json:"justify,omitempty"`
}

// DateTimeInputComponent holds the component-specific fields for a DateTimeInput.
type DateTimeInputComponent struct {
	EnableDate *bool          `json:"enableDate,omitempty"`
	EnableTime *bool          `json:"enableTime,omitempty"`
	Label      *DynamicString `json:"label,omitempty"`
	Max        *DynamicString `json:"max,omitempty"`
	Min        *DynamicString `json:"min,omitempty"`
	Value      DynamicString  `json:"value"`
}

// DividerComponent holds the component-specific fields for a Divider.
type DividerComponent struct {
	Axis DividerAxis `json:"axis,omitempty"`
}

// IconComponent holds the component-specific fields for a Icon.
type IconComponent struct {
	Name IconNameOrPath `json:"name"`
}

// ImageComponent holds the component-specific fields for a Image.
type ImageComponent struct {
	Description *DynamicString `json:"description,omitempty"`
	Fit         ImageFit       `json:"fit,omitempty"`
	URL         DynamicString  `json:"url"`
	Variant     ImageVariant   `json:"variant,omitempty"`
}

// ListComponent holds the component-specific fields for a List.
type ListComponent struct {
	Align     LayoutAlign   `json:"align,omitempty"`
	Children  ChildList     `json:"children"`
	Direction ListDirection `json:"direction,omitempty"`
}

// ModalComponent holds the component-specific fields for a Modal.
type ModalComponent struct {
	Content string `json:"content"`
	Trigger string `json:"trigger"`
}

// RowComponent holds the component-specific fields for a Row.
type RowComponent struct {
	Align    LayoutAlign   `json:"align,omitempty"`
	Children ChildList     `json:"children"`
	Justify  LayoutJustify `json:"justify,omitempty"`
}

// SliderComponent holds the component-specific fields for a Slider.
type SliderComponent struct {
	Label *DynamicString `json:"label,omitempty"`
	Max   float64        `json:"max"`
	Min   *float64       `json:"min,omitempty"`
	Value DynamicNumber  `json:"value"`
}

// TabsComponent holds the component-specific fields for a Tabs.
type TabsComponent struct {
	Tabs []TabDef `json:"tabs"`
}

// TextComponent holds the component-specific fields for a Text.
type TextComponent struct {
	Text    DynamicString `json:"text"`
	Variant TextVariant   `json:"variant,omitempty"`
}

// TextFieldComponent holds the component-specific fields for a TextField.
type TextFieldComponent struct {
	Label            DynamicString    `json:"label"`
	ValidationRegexp string           `json:"validationRegexp,omitempty"`
	Value            *DynamicString   `json:"value,omitempty"`
	Variant          TextFieldVariant `json:"variant,omitempty"`
}

// VideoComponent holds the component-specific fields for a Video.
type VideoComponent struct {
	URL DynamicString `json:"url"`
}
