// Code generated by a2uigen; DO NOT EDIT.

package v091

// ReturnType is the expected return type of a function call.
type ReturnType string

const (
	ReturnTypeString  ReturnType = "string"
	ReturnTypeNumber  ReturnType = "number"
	ReturnTypeBoolean ReturnType = "boolean"
	ReturnTypeArray   ReturnType = "array"
	ReturnTypeObject  ReturnType = "object"
	ReturnTypeAny     ReturnType = "any"
	ReturnTypeVoid    ReturnType = "void"
)

// IconName identifies a built-in icon.
type IconName string

// ButtonVariant defines the allowed values for the ButtonVariant enum.
type ButtonVariant string

const (
	ButtonVariantDefault    ButtonVariant = "default"
	ButtonVariantPrimary    ButtonVariant = "primary"
	ButtonVariantBorderless ButtonVariant = "borderless"
)

// ChoicePickerDisplayStyle defines the allowed values for the ChoicePickerDisplayStyle enum.
type ChoicePickerDisplayStyle string

const (
	ChoicePickerDisplayStyleCheckbox ChoicePickerDisplayStyle = "checkbox"
	ChoicePickerDisplayStyleChips    ChoicePickerDisplayStyle = "chips"
)

// ChoicePickerVariant defines the allowed values for the ChoicePickerVariant enum.
type ChoicePickerVariant string

const (
	ChoicePickerVariantMultipleSelection ChoicePickerVariant = "multipleSelection"
	ChoicePickerVariantMutuallyExclusive ChoicePickerVariant = "mutuallyExclusive"
)

// DividerAxis defines the allowed values for the DividerAxis enum.
type DividerAxis string

const (
	DividerAxisHorizontal DividerAxis = "horizontal"
	DividerAxisVertical   DividerAxis = "vertical"
)

// ImageFit defines the allowed values for the ImageFit enum.
type ImageFit string

const (
	ImageFitContain   ImageFit = "contain"
	ImageFitCover     ImageFit = "cover"
	ImageFitFill      ImageFit = "fill"
	ImageFitNone      ImageFit = "none"
	ImageFitScaleDown ImageFit = "scaleDown"
)

// ImageVariant defines the allowed values for the ImageVariant enum.
type ImageVariant string

const (
	ImageVariantIcon          ImageVariant = "icon"
	ImageVariantAvatar        ImageVariant = "avatar"
	ImageVariantSmallFeature  ImageVariant = "smallFeature"
	ImageVariantMediumFeature ImageVariant = "mediumFeature"
	ImageVariantLargeFeature  ImageVariant = "largeFeature"
	ImageVariantHeader        ImageVariant = "header"
)

// LayoutAlign defines the allowed values for the LayoutAlign enum.
type LayoutAlign string

const (
	LayoutAlignCenter  LayoutAlign = "center"
	LayoutAlignEnd     LayoutAlign = "end"
	LayoutAlignStart   LayoutAlign = "start"
	LayoutAlignStretch LayoutAlign = "stretch"
)

// LayoutJustify defines the allowed values for the LayoutJustify enum.
type LayoutJustify string

const (
	LayoutJustifyStart        LayoutJustify = "start"
	LayoutJustifyCenter       LayoutJustify = "center"
	LayoutJustifyEnd          LayoutJustify = "end"
	LayoutJustifySpaceBetween LayoutJustify = "spaceBetween"
	LayoutJustifySpaceAround  LayoutJustify = "spaceAround"
	LayoutJustifySpaceEvenly  LayoutJustify = "spaceEvenly"
	LayoutJustifyStretch      LayoutJustify = "stretch"
)

// ListDirection defines the allowed values for the ListDirection enum.
type ListDirection string

const (
	ListDirectionVertical   ListDirection = "vertical"
	ListDirectionHorizontal ListDirection = "horizontal"
)

// TextFieldVariant defines the allowed values for the TextFieldVariant enum.
type TextFieldVariant string

const (
	TextFieldVariantLongText  TextFieldVariant = "longText"
	TextFieldVariantNumber    TextFieldVariant = "number"
	TextFieldVariantShortText TextFieldVariant = "shortText"
	TextFieldVariantObscured  TextFieldVariant = "obscured"
)

// TextVariant defines the allowed values for the TextVariant enum.
type TextVariant string

const (
	TextVariantH1      TextVariant = "h1"
	TextVariantH2      TextVariant = "h2"
	TextVariantH3      TextVariant = "h3"
	TextVariantH4      TextVariant = "h4"
	TextVariantH5      TextVariant = "h5"
	TextVariantCaption TextVariant = "caption"
	TextVariantBody    TextVariant = "body"
)
