// Code generated by a2uigen; DO NOT EDIT.

package v091

// And creates a function call for "and".
// Performs a logical AND operation on a list of boolean values.
func And(values []DynamicBoolean) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "and",
		Args: map[string]any{
			"values": values,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// Email creates a function call for "email".
// Checks that the value is a valid email address.
func Email(value DynamicString) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "email",
		Args: map[string]any{
			"value": value,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// FormatCurrency creates a function call for "formatCurrency".
// Formats a number as a currency string.
func FormatCurrency(currency DynamicString, decimals DynamicNumber, grouping DynamicBoolean, value DynamicNumber) DynamicString {
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatCurrency",
		Args: map[string]any{
			"currency": currency,
			"decimals": decimals,
			"grouping": grouping,
			"value":    value,
		},
		ReturnType: ReturnTypeString,
	}}
}

// FormatDate creates a function call for "formatDate".
// Formats a timestamp into a string using a pattern.
func FormatDate(format DynamicString, value DynamicValue) DynamicString {
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatDate",
		Args: map[string]any{
			"format": format,
			"value":  value,
		},
		ReturnType: ReturnTypeString,
	}}
}

// FormatNumber creates a function call for "formatNumber".
// Formats a number with the specified grouping and decimal precision.
func FormatNumber(decimals DynamicNumber, grouping DynamicBoolean, value DynamicNumber) DynamicString {
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatNumber",
		Args: map[string]any{
			"decimals": decimals,
			"grouping": grouping,
			"value":    value,
		},
		ReturnType: ReturnTypeString,
	}}
}

// FormatString creates a function call for "formatString".
// Performs string interpolation of data model values and other functions in the catalog functions list and returns the resulting string. The value string can contain interpolated expressions in the `${expression}` format. Supported expression types include: JSON Pointer paths to the data model (e.g., `${/absolute/path}` or `${relative/path}`), and client-side function calls (e.g., `${now()}`). Function arguments must be named (e.g., `${formatDate(value:${/currentDate}, format:'MM-dd')}`). To include a literal `${` sequence, escape it as `\${`.
func FormatString(value DynamicString) DynamicString {
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "formatString",
		Args: map[string]any{
			"value": value,
		},
		ReturnType: ReturnTypeString,
	}}
}

// Length creates a function call for "length".
// Checks string length constraints.
func Length(max int, min int, value DynamicString) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "length",
		Args: map[string]any{
			"max":   max,
			"min":   min,
			"value": value,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// Not creates a function call for "not".
// Performs a logical NOT operation on a boolean value.
func Not(value DynamicBoolean) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "not",
		Args: map[string]any{
			"value": value,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// Numeric creates a function call for "numeric".
// Checks numeric range constraints.
func Numeric(max float64, min float64, value DynamicNumber) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "numeric",
		Args: map[string]any{
			"max":   max,
			"min":   min,
			"value": value,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// OpenURL creates a function call for "openUrl".
// Opens the specified URL in a browser or handler. This function has no return value.
func OpenURL(url string) Action {
	return Action{FunctionCall: &FunctionCall{
		Call: "openUrl",
		Args: map[string]any{
			"url": url,
		},
		ReturnType: ReturnTypeVoid,
	}}
}

// Or creates a function call for "or".
// Performs a logical OR operation on a list of boolean values.
func Or(values []DynamicBoolean) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "or",
		Args: map[string]any{
			"values": values,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// Pluralize creates a function call for "pluralize".
// Returns a localized string based on the Common Locale Data Repository (CLDR) plural category of the count (zero, one, two, few, many, other). Requires an 'other' fallback. For English, just use 'one' and 'other'.
func Pluralize(few DynamicString, many DynamicString, one DynamicString, other DynamicString, two DynamicString, value DynamicNumber, zero DynamicString) DynamicString {
	return DynamicString{FunctionCall: &FunctionCall{
		Call: "pluralize",
		Args: map[string]any{
			"few":   few,
			"many":  many,
			"one":   one,
			"other": other,
			"two":   two,
			"value": value,
			"zero":  zero,
		},
		ReturnType: ReturnTypeString,
	}}
}

// Regex creates a function call for "regex".
// Checks that the value matches a regular expression string.
func Regex(pattern string, value DynamicString) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "regex",
		Args: map[string]any{
			"pattern": pattern,
			"value":   value,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}

// Required creates a function call for "required".
// Checks that the value is not null, undefined, or empty.
func Required(value DynamicValue) DynamicBoolean {
	return DynamicBoolean{FunctionCall: &FunctionCall{
		Call: "required",
		Args: map[string]any{
			"value": value,
		},
		ReturnType: ReturnTypeBoolean,
	}}
}
