package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

// generateBridge writes a2ui.go in the root a2ui package, declaring a
// deprecated, inlinable forwarder for every exported identifier of the
// version package pkg. Running go fix in client code then rewrites uses of
// the root package to pkg.
func generateBridge(out, module, a2uiDir, buildDir, a2uiImport, pkg string) error {
	cfg, err := resolveOutputConfig(out, module, a2uiDir, buildDir, a2uiImport, pkg)
	if err != nil {
		return err
	}
	src, err := bridgeSource(filepath.Join(out, cfg.A2UIDir, pkg), pkg, cfg.VersionImport)
	if err != nil {
		return fmt.Errorf("bridge %s: %w", pkg, err)
	}
	outPath := filepath.Join(out, cfg.A2UIDir, "a2ui.go")
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		return err
	}
	fmt.Println(outPath)
	return nil
}

func bridgeSource(dir, pkg, pkgImport string) ([]byte, error) {
	fset := token.NewFileSet()
	names, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	var files []*ast.File
	for _, name := range names {
		if strings.HasSuffix(name, "_test.go") || filepath.Base(name) == "gen.go" {
			continue
		}
		f, err := parser.ParseFile(fset, name, nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}

	// Exported type names are qualified with pkg wherever they appear in
	// forwarded function signatures.
	types := make(map[string]bool)
	for _, f := range files {
		for _, decl := range f.Decls {
			if d, ok := decl.(*ast.GenDecl); ok && d.Tok == token.TYPE {
				for _, spec := range d.Specs {
					if ts := spec.(*ast.TypeSpec); ts.Name.IsExported() {
						types[ts.Name.Name] = true
					}
				}
			}
		}
	}

	var (
		body    bytes.Buffer
		imports = map[string]bool{pkgImport: true}
	)
	deprecated := func(name string) {
		fmt.Fprintf(&body, "\n// Deprecated: Use [%s.%s]. The root package becomes the A2UI v1.0 API in the next release.\n//\n//go:fix inline\n", pkg, name)
	}
	for _, f := range files {
		fileImports := make(map[string]string) // name -> path
		for _, imp := range f.Imports {
			path, _ := strconv.Unquote(imp.Path.Value)
			name := path[strings.LastIndex(path, "/")+1:]
			if imp.Name != nil {
				name = imp.Name.Name
			}
			fileImports[name] = path
		}
		qualify := func(n ast.Node) (string, error) {
			n = qualifyTypes(n, pkg, types)
			var err error
			ast.Inspect(n, func(n ast.Node) bool {
				if sel, ok := n.(*ast.SelectorExpr); ok {
					if x, ok := sel.X.(*ast.Ident); ok && x.Name != pkg {
						path, ok := fileImports[x.Name]
						if !ok {
							err = fmt.Errorf("unknown package %s", x.Name)
						}
						imports[path] = true
					}
				}
				return true
			})
			return nodeString(fset, n), err
		}

		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch spec := spec.(type) {
					case *ast.TypeSpec:
						if !spec.Name.IsExported() {
							continue
						}
						name := spec.Name.Name
						deprecated(name)
						if spec.TypeParams == nil {
							fmt.Fprintf(&body, "type %s = %s.%s\n", name, pkg, name)
							continue
						}
						params, err := typeParamList(spec.TypeParams, qualify)
						if err != nil {
							return nil, err
						}
						fmt.Fprintf(&body, "type %s[%s] = %s.%s[%s]\n", name, params, pkg, name, strings.Join(fieldNames(spec.TypeParams), ", "))
					case *ast.ValueSpec:
						for _, id := range spec.Names {
							if !id.IsExported() {
								continue
							}
							if d.Tok == token.VAR {
								return nil, fmt.Errorf("cannot forward variable %s", id.Name)
							}
							deprecated(id.Name)
							fmt.Fprintf(&body, "const %s = %s.%s\n", id.Name, pkg, id.Name)
						}
					}
				}
			case *ast.FuncDecl:
				if d.Recv != nil || !d.Name.IsExported() {
					continue
				}
				fn, err := forwardFunc(d, pkg, qualify)
				if err != nil {
					return nil, err
				}
				deprecated(d.Name.Name)
				body.WriteString(fn)
			}
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by a2uigen; DO NOT EDIT.\n\npackage a2ui\n\nimport (\n")
	for _, path := range slices.Sorted(maps.Keys(imports)) {
		fmt.Fprintf(&buf, "\t%q\n", path)
	}
	buf.WriteString(")\n")
	buf.Write(body.Bytes())
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w\n%s", err, buf.Bytes())
	}
	return src, nil
}

// forwardFunc returns a function with d's signature that calls pkg's d.
func forwardFunc(d *ast.FuncDecl, pkg string, qualify func(ast.Node) (string, error)) (string, error) {
	var (
		params []string
		args   []string
	)
	for i, field := range d.Type.Params.List {
		typ, err := qualify(field.Type)
		if err != nil {
			return "", err
		}
		names := fieldNames(&ast.FieldList{List: []*ast.Field{field}})
		if len(field.Names) == 0 {
			names = []string{fmt.Sprintf("p%d", i)}
		}
		for _, name := range names {
			params = append(params, name+" "+typ)
			if _, ok := field.Type.(*ast.Ellipsis); ok {
				name += "..."
			}
			args = append(args, name)
		}
	}
	var results string
	if d.Type.Results != nil {
		var list []string
		for _, field := range d.Type.Results.List {
			typ, err := qualify(field.Type)
			if err != nil {
				return "", err
			}
			for range max(1, len(field.Names)) {
				list = append(list, typ)
			}
		}
		results = strings.Join(list, ", ")
		if len(list) > 1 {
			results = "(" + results + ")"
		}
	}
	var typeParams, inst string
	if d.Type.TypeParams != nil {
		tp, err := typeParamList(d.Type.TypeParams, qualify)
		if err != nil {
			return "", err
		}
		typeParams = "[" + tp + "]"
		inst = "[" + strings.Join(fieldNames(d.Type.TypeParams), ", ") + "]"
	}
	call := fmt.Sprintf("%s.%s%s(%s)", pkg, d.Name.Name, inst, strings.Join(args, ", "))
	if results != "" {
		call = "return " + call
	}
	return fmt.Sprintf("func %s%s(%s) %s {\n\t%s\n}\n", d.Name.Name, typeParams, strings.Join(params, ", "), results, call), nil
}

// qualifyTypes returns a copy of the type expression n with references
// to the exported types of pkg qualified by pkg.
func qualifyTypes(n ast.Node, pkg string, types map[string]bool) ast.Node {
	switch n := n.(type) {
	case *ast.Ident:
		if types[n.Name] {
			return &ast.SelectorExpr{X: ast.NewIdent(pkg), Sel: ast.NewIdent(n.Name)}
		}
		return n
	case *ast.StarExpr:
		return &ast.StarExpr{X: qualifyTypes(n.X, pkg, types).(ast.Expr)}
	case *ast.ArrayType:
		return &ast.ArrayType{Len: n.Len, Elt: qualifyTypes(n.Elt, pkg, types).(ast.Expr)}
	case *ast.MapType:
		return &ast.MapType{Key: qualifyTypes(n.Key, pkg, types).(ast.Expr), Value: qualifyTypes(n.Value, pkg, types).(ast.Expr)}
	case *ast.Ellipsis:
		return &ast.Ellipsis{Elt: qualifyTypes(n.Elt, pkg, types).(ast.Expr)}
	case *ast.ChanType:
		return &ast.ChanType{Dir: n.Dir, Value: qualifyTypes(n.Value, pkg, types).(ast.Expr)}
	case *ast.IndexExpr:
		return &ast.IndexExpr{X: qualifyTypes(n.X, pkg, types).(ast.Expr), Index: qualifyTypes(n.Index, pkg, types).(ast.Expr)}
	case *ast.IndexListExpr:
		list := make([]ast.Expr, len(n.Indices))
		for i, x := range n.Indices {
			list[i] = qualifyTypes(x, pkg, types).(ast.Expr)
		}
		return &ast.IndexListExpr{X: qualifyTypes(n.X, pkg, types).(ast.Expr), Indices: list}
	case *ast.FuncType:
		return &ast.FuncType{
			TypeParams: qualifyFields(n.TypeParams, pkg, types),
			Params:     qualifyFields(n.Params, pkg, types),
			Results:    qualifyFields(n.Results, pkg, types),
		}
	case *ast.FieldList:
		return qualifyFields(n, pkg, types)
	case *ast.BinaryExpr: // type constraint unions
		return &ast.BinaryExpr{X: qualifyTypes(n.X, pkg, types).(ast.Expr), Op: n.Op, Y: qualifyTypes(n.Y, pkg, types).(ast.Expr)}
	case *ast.UnaryExpr: // ~T
		return &ast.UnaryExpr{Op: n.Op, X: qualifyTypes(n.X, pkg, types).(ast.Expr)}
	default:
		// Selector expressions, struct and interface literals are
		// printed as written.
		return n
	}
}

func qualifyFields(fl *ast.FieldList, pkg string, types map[string]bool) *ast.FieldList {
	if fl == nil {
		return nil
	}
	out := &ast.FieldList{}
	for _, f := range fl.List {
		out.List = append(out.List, &ast.Field{Names: f.Names, Type: qualifyTypes(f.Type, pkg, types).(ast.Expr)})
	}
	return out
}

// typeParamList returns the type parameter list fl without brackets.
func typeParamList(fl *ast.FieldList, qualify func(ast.Node) (string, error)) (string, error) {
	var list []string
	for _, f := range fl.List {
		constraint, err := qualify(f.Type)
		if err != nil {
			return "", err
		}
		list = append(list, strings.Join(fieldNames(&ast.FieldList{List: []*ast.Field{f}}), ", ")+" "+constraint)
	}
	return strings.Join(list, ", "), nil
}

func fieldNames(fl *ast.FieldList) []string {
	var names []string
	for _, f := range fl.List {
		for _, id := range f.Names {
			names = append(names, id.Name)
		}
	}
	return names
}

func nodeString(fset *token.FileSet, n ast.Node) string {
	var buf bytes.Buffer
	printer.Fprint(&buf, fset, n)
	return buf.String()
}
