package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestResolveOutputConfigDefaultLayout(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/a2ui\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	cfg, err := resolveOutputConfig(dir, "", "a2ui", "a2uibuild", "")
	if err != nil {
		t.Fatal(err)
	}
	if cfg.A2UIDir != "a2ui" {
		t.Fatalf("A2UIDir = %q, want a2ui", cfg.A2UIDir)
	}
	if cfg.A2UIBuildDir != "a2uibuild" {
		t.Fatalf("A2UIBuildDir = %q, want a2uibuild", cfg.A2UIBuildDir)
	}
	if cfg.A2UIImport != "example.com/a2ui/a2ui" {
		t.Fatalf("A2UIImport = %q, want example.com/a2ui/a2ui", cfg.A2UIImport)
	}
}

func TestResolveOutputConfigRootLayout(t *testing.T) {
	dir := t.TempDir()

	cfg, err := resolveOutputConfig(dir, "example.com/root", ".", "a2uibuild", "")
	if err != nil {
		t.Fatal(err)
	}
	if cfg.A2UIDir != "." {
		t.Fatalf("A2UIDir = %q, want .", cfg.A2UIDir)
	}
	if cfg.A2UIImport != "example.com/root" {
		t.Fatalf("A2UIImport = %q, want example.com/root", cfg.A2UIImport)
	}
}

func TestResolveOutputConfigExplicitA2UIImport(t *testing.T) {
	dir := t.TempDir()

	cfg, err := resolveOutputConfig(dir, "", "generated/a2ui", "generated/a2uibuild", "example.com/custom/a2ui")
	if err != nil {
		t.Fatal(err)
	}
	if cfg.A2UIImport != "example.com/custom/a2ui" {
		t.Fatalf("A2UIImport = %q, want example.com/custom/a2ui", cfg.A2UIImport)
	}
}

func TestGenerateSDKRootLayout(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/root\n\ngo 1.25\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	// The previous release had v09 and v091 packages, and its root
	// package forwarded to v09. The downstream module keeps its own files
	// next to the generated ones, in v091 too.
	seed := map[string]string{
		"a2ui.go":                              "// Code generated by a2uigen; DO NOT EDIT.\n\npackage a2ui\n",
		"generate.go":                          "package a2ui\n\n//go:generate a2uigen -sdk -out=. -a2ui-dir=.\n",
		filepath.Join("testdata", "keep.json"): "{}\n",
		filepath.Join("v091", "extra.go"):      "package v091\n",
	}
	stale := map[string]string{
		filepath.Join("v09", "zz_component.go"):                                             "// Code generated by a2uigen; DO NOT EDIT.\n\npackage v09\n",
		filepath.Join("v09", "message.go"):                                                  "package v09\n",
		filepath.Join("v09", "testdata", "v0_9", "catalogs", "basic", "examples", "a.json"): "{}\n",
		filepath.Join("v091", "zz_component.go"):                                            "// Code generated by a2uigen; DO NOT EDIT.\n\npackage v091\n",
		filepath.Join("v091", "doc.go"):                                                     "package v091\n",
		filepath.Join("v10", "zz_enum.go"):                                                  "// Code generated by a2uigen; DO NOT EDIT.\n\npackage v10\n",
	}
	for name, data := range stale {
		seed[name] = data
	}
	for name, data := range seed {
		if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dir, name), []byte(data), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if err := generateSDK(dir, "example.com/root", ".", "a2uibuild", "", "", ""); err != nil {
		t.Fatal(err)
	}
	for _, stale := range []string{"v09", "v10", filepath.Join("v091", "testdata")} {
		if _, err := os.Stat(filepath.Join(dir, stale)); !os.IsNotExist(err) {
			t.Fatalf("stale directory %s not removed (err = %v)", stale, err)
		}
	}
	for name := range stale {
		if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
			t.Fatalf("stale file %s not removed (err = %v)", name, err)
		}
	}

	checks := []struct {
		path string
		want string
	}{
		{"message.go", "package a2ui\n"},
		{"zz_component.go", "package a2ui\n"},
		{"zz_component.go", `const BasicCatalogID = "https://a2ui.org/specification/v1_0/catalogs/basic/catalog.json"`},
		{filepath.Join("a2uibuild", "zz_builders.go"), `import "example.com/root"`},
		{filepath.Join("a2uischema", "manager.go"), `"example.com/root"`},
		{filepath.Join("a2uistate", "example_test.go"), `"example.com/root/a2uistate"`},
		{filepath.Join("a2uistate", "eval.go"), `"example.com/root"`},
		{"zz_function.go", "func Length(value DynamicString, max *int, min *int) DynamicValidationResult {"},
	}
	for _, check := range checks {
		data, err := os.ReadFile(filepath.Join(dir, check.path))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), check.want) {
			t.Fatalf("%s does not contain %q", check.path, check.want)
		}
	}

	for _, path := range []string{"a2ui.go", "gen.go", filepath.Join("a2uischema", "gen.go")} {
		if _, err := os.Stat(filepath.Join(dir, path)); !os.IsNotExist(err) {
			t.Fatalf("%s present in SDK output (err = %v)", path, err)
		}
	}
	for _, name := range []string{"generate.go", filepath.Join("testdata", "keep.json"), filepath.Join("v091", "extra.go")} {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("hand-written %s not preserved: %v", name, err)
		}
		if string(data) != seed[name] {
			t.Fatalf("hand-written %s modified:\n%s", name, data)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "testdata", "v1_0", "catalogs", "basic", "examples")); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "a2uischema", "gen.go")); !os.IsNotExist(err) {
		t.Fatalf("a2uischema/gen.go copied into SDK output (err = %v)", err)
	}

	for _, path := range []string{
		filepath.Join(dir, "message.go"),
		filepath.Join(dir, "a2uischema", "manager.go"),
		filepath.Join(dir, "a2uibuild", "surface.go"),
		filepath.Join(dir, "a2uistate", "example_test.go"),
		filepath.Join(dir, "a2uistate", "eval.go"),
	} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(data), "github.com/a2ui-project/a2ui/go") {
			t.Fatalf("%s contains upstream module import", path)
		}
	}
}

func TestParseFunctionArgs(t *testing.T) {
	tests := []struct {
		name   string
		schema string
		want   []FuncArg
	}{
		{
			"required order then optional by name",
			`{"returnType": "string", "properties": {"args": {
				"required": ["value", "other"],
				"properties": {
					"zero": {"$ref": "common_types.json#/$defs/DynamicString"},
					"other": {"$ref": "common_types.json#/$defs/DynamicString"},
					"one": {"$ref": "common_types.json#/$defs/DynamicString"},
					"value": {"$ref": "common_types.json#/$defs/DynamicNumber"}
				}
			}}}`,
			[]FuncArg{
				{"value", "Value", "DynamicNumber", true},
				{"other", "Other", "DynamicString", true},
				{"one", "One", "DynamicString", false},
				{"zero", "Zero", "DynamicString", false},
			},
		},
		{
			"optional scalars are pointers",
			`{"returnType": "validationResult", "properties": {"args": {
				"required": ["value", "pattern"],
				"properties": {
					"value": {"$ref": "common_types.json#/$defs/DynamicString"},
					"pattern": {"type": "string"},
					"min": {"type": "integer"},
					"max": {"type": "number"},
					"strict": {"type": "boolean"},
					"flags": {"type": "string"}
				}
			}}}`,
			[]FuncArg{
				{"value", "Value", "DynamicString", true},
				{"pattern", "Pattern", "string", true},
				{"flags", "Flags", "*string", false},
				{"max", "Max", "*float64", false},
				{"min", "Min", "*int", false},
				{"strict", "Strict", "*bool", false},
			},
		},
		{
			"no required list",
			`{"returnType": "string", "properties": {"args": {"properties": {
				"b": {"type": "integer"},
				"a": {"$ref": "common_types.json#/$defs/DynamicBoolean"}
			}}}}`,
			[]FuncArg{
				{"a", "A", "DynamicBoolean", false},
				{"b", "B", "*int", false},
			},
		},
	}
	for _, tt := range tests {
		fd, err := parseFunction("f", json.RawMessage(tt.schema))
		if err != nil {
			t.Errorf("%s: %v", tt.name, err)
			continue
		}
		if len(fd.Args) != len(tt.want) {
			t.Errorf("%s: args = %+v, want %+v", tt.name, fd.Args, tt.want)
			continue
		}
		for i := range tt.want {
			if fd.Args[i] != tt.want[i] {
				t.Errorf("%s: arg %d = %+v, want %+v", tt.name, i, fd.Args[i], tt.want[i])
			}
		}
	}
}

func TestFuncArgSetCond(t *testing.T) {
	tests := []struct {
		typ, want string
	}{
		{"*int", "x != nil"},
		{"[]DynamicBoolean", "x != nil"},
		{"DynamicNumber", "x != (DynamicNumber{})"},
		{"DynamicStringList", "x.Literal != nil || x.Binding != nil || x.FunctionCall != nil"},
		{"DynamicValue", "x.String != nil || x.Number != nil || x.Bool != nil || x.Array != nil || x.Binding != nil || x.FunctionCall != nil"},
	}
	for _, tt := range tests {
		if got := (FuncArg{Name: "x", GoType: tt.typ}).SetCond(); got != tt.want {
			t.Errorf("SetCond for %s = %q, want %q", tt.typ, got, tt.want)
		}
	}
}
