// Code generated by a2uigen; DO NOT EDIT.

// Package a2uibuild provides convenience constructors for A2UI components.
package a2uibuild

import "github.com/a2ui-project/a2ui/go/a2ui"

// AudioPlayer creates a new [a2ui.Component] of type AudioPlayer with the given id.
func AudioPlayer(id string, url a2ui.DynamicString) a2ui.Component {
	return a2ui.Component{
		ID: id,
		AudioPlayer: &a2ui.AudioPlayerComponent{
			URL: url,
		},
	}
}

// Button creates a new [a2ui.Component] of type Button with the given id.
func Button(id string, action a2ui.Action, child string) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Button: &a2ui.ButtonComponent{
			Action: action,
			Child:  child,
		},
	}
}

// Card creates a new [a2ui.Component] of type Card with the given id.
func Card(id string, child string) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Card: &a2ui.CardComponent{
			Child: child,
		},
	}
}

// CheckBox creates a new [a2ui.Component] of type CheckBox with the given id.
func CheckBox(id string, label a2ui.DynamicString, value a2ui.DynamicBoolean) a2ui.Component {
	return a2ui.Component{
		ID: id,
		CheckBox: &a2ui.CheckBoxComponent{
			Label: label,
			Value: value,
		},
	}
}

// ChoicePicker creates a new [a2ui.Component] of type ChoicePicker with the given id.
func ChoicePicker(id string, options []a2ui.ChoiceOption, value a2ui.DynamicStringList) a2ui.Component {
	return a2ui.Component{
		ID: id,
		ChoicePicker: &a2ui.ChoicePickerComponent{
			Options: options,
			Value:   value,
		},
	}
}

// Column creates a new [a2ui.Component] of type Column with the given id.
func Column(id string, children a2ui.ChildList) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Column: &a2ui.ColumnComponent{
			Children: children,
		},
	}
}

// DateTimeInput creates a new [a2ui.Component] of type DateTimeInput with the given id.
func DateTimeInput(id string, value a2ui.DynamicString) a2ui.Component {
	return a2ui.Component{
		ID: id,
		DateTimeInput: &a2ui.DateTimeInputComponent{
			Value: value,
		},
	}
}

// Divider creates a new [a2ui.Component] of type Divider with the given id.
func Divider(id string) a2ui.Component {
	return a2ui.Component{
		ID:      id,
		Divider: &a2ui.DividerComponent{},
	}
}

// Icon creates a new [a2ui.Component] of type Icon with the given id.
func Icon(id string, name a2ui.IconNameOrPath) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Icon: &a2ui.IconComponent{
			Name: name,
		},
	}
}

// Image creates a new [a2ui.Component] of type Image with the given id.
func Image(id string, url a2ui.DynamicString) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Image: &a2ui.ImageComponent{
			URL: url,
		},
	}
}

// List creates a new [a2ui.Component] of type List with the given id.
func List(id string, children a2ui.ChildList) a2ui.Component {
	return a2ui.Component{
		ID: id,
		List: &a2ui.ListComponent{
			Children: children,
		},
	}
}

// Modal creates a new [a2ui.Component] of type Modal with the given id.
func Modal(id string, content string, trigger string) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Modal: &a2ui.ModalComponent{
			Content: content,
			Trigger: trigger,
		},
	}
}

// Row creates a new [a2ui.Component] of type Row with the given id.
func Row(id string, children a2ui.ChildList) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Row: &a2ui.RowComponent{
			Children: children,
		},
	}
}

// Slider creates a new [a2ui.Component] of type Slider with the given id.
func Slider(id string, max float64, value a2ui.DynamicNumber) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Slider: &a2ui.SliderComponent{
			Max:   max,
			Value: value,
		},
	}
}

// Tabs creates a new [a2ui.Component] of type Tabs with the given id.
func Tabs(id string, tabs []a2ui.TabDef) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Tabs: &a2ui.TabsComponent{
			Tabs: tabs,
		},
	}
}

// Text creates a new [a2ui.Component] of type Text with the given id.
func Text(id string, text a2ui.DynamicString) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Text: &a2ui.TextComponent{
			Text: text,
		},
	}
}

// TextField creates a new [a2ui.Component] of type TextField with the given id.
func TextField(id string, label a2ui.DynamicString) a2ui.Component {
	return a2ui.Component{
		ID: id,
		TextField: &a2ui.TextFieldComponent{
			Label: label,
		},
	}
}

// Video creates a new [a2ui.Component] of type Video with the given id.
func Video(id string, url a2ui.DynamicString) a2ui.Component {
	return a2ui.Component{
		ID: id,
		Video: &a2ui.VideoComponent{
			URL: url,
		},
	}
}
