// Code generated by a2uigen; DO NOT EDIT.

// Package a2uibuild provides convenience constructors for A2UI components.
package a2uibuild

import "github.com/a2ui-project/a2ui/go/a2ui/v09"

// AudioPlayer creates a new [v09.Component] of type AudioPlayer with the given id.
func AudioPlayer(id string, url v09.DynamicString) v09.Component {
	return v09.Component{
		ID: id,
		AudioPlayer: &v09.AudioPlayerComponent{
			URL: url,
		},
	}
}

// Button creates a new [v09.Component] of type Button with the given id.
func Button(id string, action v09.Action, child string) v09.Component {
	return v09.Component{
		ID: id,
		Button: &v09.ButtonComponent{
			Action: action,
			Child:  child,
		},
	}
}

// Card creates a new [v09.Component] of type Card with the given id.
func Card(id string, child string) v09.Component {
	return v09.Component{
		ID: id,
		Card: &v09.CardComponent{
			Child: child,
		},
	}
}

// CheckBox creates a new [v09.Component] of type CheckBox with the given id.
func CheckBox(id string, label v09.DynamicString, value v09.DynamicBoolean) v09.Component {
	return v09.Component{
		ID: id,
		CheckBox: &v09.CheckBoxComponent{
			Label: label,
			Value: value,
		},
	}
}

// ChoicePicker creates a new [v09.Component] of type ChoicePicker with the given id.
func ChoicePicker(id string, options []v09.ChoiceOption, value v09.DynamicStringList) v09.Component {
	return v09.Component{
		ID: id,
		ChoicePicker: &v09.ChoicePickerComponent{
			Options: options,
			Value:   value,
		},
	}
}

// Column creates a new [v09.Component] of type Column with the given id.
func Column(id string, children v09.ChildList) v09.Component {
	return v09.Component{
		ID: id,
		Column: &v09.ColumnComponent{
			Children: children,
		},
	}
}

// DateTimeInput creates a new [v09.Component] of type DateTimeInput with the given id.
func DateTimeInput(id string, value v09.DynamicString) v09.Component {
	return v09.Component{
		ID: id,
		DateTimeInput: &v09.DateTimeInputComponent{
			Value: value,
		},
	}
}

// Divider creates a new [v09.Component] of type Divider with the given id.
func Divider(id string) v09.Component {
	return v09.Component{
		ID:      id,
		Divider: &v09.DividerComponent{},
	}
}

// Icon creates a new [v09.Component] of type Icon with the given id.
func Icon(id string, name v09.IconNameOrPath) v09.Component {
	return v09.Component{
		ID: id,
		Icon: &v09.IconComponent{
			Name: name,
		},
	}
}

// Image creates a new [v09.Component] of type Image with the given id.
func Image(id string, url v09.DynamicString) v09.Component {
	return v09.Component{
		ID: id,
		Image: &v09.ImageComponent{
			URL: url,
		},
	}
}

// List creates a new [v09.Component] of type List with the given id.
func List(id string, children v09.ChildList) v09.Component {
	return v09.Component{
		ID: id,
		List: &v09.ListComponent{
			Children: children,
		},
	}
}

// Modal creates a new [v09.Component] of type Modal with the given id.
func Modal(id string, content string, trigger string) v09.Component {
	return v09.Component{
		ID: id,
		Modal: &v09.ModalComponent{
			Content: content,
			Trigger: trigger,
		},
	}
}

// Row creates a new [v09.Component] of type Row with the given id.
func Row(id string, children v09.ChildList) v09.Component {
	return v09.Component{
		ID: id,
		Row: &v09.RowComponent{
			Children: children,
		},
	}
}

// Slider creates a new [v09.Component] of type Slider with the given id.
func Slider(id string, max float64, value v09.DynamicNumber) v09.Component {
	return v09.Component{
		ID: id,
		Slider: &v09.SliderComponent{
			Max:   max,
			Value: value,
		},
	}
}

// Tabs creates a new [v09.Component] of type Tabs with the given id.
func Tabs(id string, tabs []v09.TabDef) v09.Component {
	return v09.Component{
		ID: id,
		Tabs: &v09.TabsComponent{
			Tabs: tabs,
		},
	}
}

// Text creates a new [v09.Component] of type Text with the given id.
func Text(id string, text v09.DynamicString) v09.Component {
	return v09.Component{
		ID: id,
		Text: &v09.TextComponent{
			Text: text,
		},
	}
}

// TextField creates a new [v09.Component] of type TextField with the given id.
func TextField(id string, label v09.DynamicString) v09.Component {
	return v09.Component{
		ID: id,
		TextField: &v09.TextFieldComponent{
			Label: label,
		},
	}
}

// Video creates a new [v09.Component] of type Video with the given id.
func Video(id string, url v09.DynamicString) v09.Component {
	return v09.Component{
		ID: id,
		Video: &v09.VideoComponent{
			URL: url,
		},
	}
}
